### ISSUE TITLE
tmrw's Roadmap

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/tmrw#1]
This issue contains details & features for upcoming releases of **tmrw**.

## Core
- [ ] `tmrw`: Tagged template function accepting markup.
- [ ] `onEvent`: Attribute for listening to events on elements.
- [ ] `useSignal`: Hook for creating reactive state.
- [ ] `useEffect`: Hook for creating listeners of state.
- [ ] `useContext`: Expose reactive state to all child components.
- [ ] `useRef`: Create non-reactive state.

## CI/CD
- [ ] Test/Lint/Format Action: Uses Deno to verify PRs and commits.
- [ ] JSR Publish Action: Publishes to JSR when Releases are created.
